Document: xeve-base
Title: Debian xeve-base Manual
Author: <insert document author here>
Abstract: This manual describes what xeve-base is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xeve-base/xeve-base.sgml.gz

Format: postscript
Files: /usr/share/doc/xeve-base/xeve-base.ps.gz

Format: text
Files: /usr/share/doc/xeve-base/xeve-base.text.gz

Format: HTML
Index: /usr/share/doc/xeve-base/html/index.html
Files: /usr/share/doc/xeve-base/html/*.html
